export const GOOGLE_AUTH_ERROR_CODE = {
  MALFORMED_TOKEN: 'G-0001',
  GOOGLE_SERVER_ERROR: 'G-0002',
  INVALID_SIGNATURE: 'G-0003',
  TOKEN_EXPIRED_OR_INVALID: 'G-0004',
  TOKEN_HAS_NOT_VALID_EMAIL: 'G-0005',
} as const

export type GoogleAuthErrorCode =
  (typeof GOOGLE_AUTH_ERROR_CODE)[keyof typeof GOOGLE_AUTH_ERROR_CODE]
