export const COMMENT_ERROR_CODE = {
  CONTENT_IS_EMPTY: 'C-0001',
  CONTENT_IS_TOO_LONG: 'C-0002',
  COMMENT_REPLY_NOT_ALLOWED: 'C-0003',
  COMMENT_NOT_FOUND: 'C-0004',
  COMMENT_PARENT_ID_NOT_FOUND: 'C-0005',
  COMMENT_NOT_WRITER: 'C-0006',
} as const

export type CommentErrorCode = (typeof COMMENT_ERROR_CODE)[keyof typeof COMMENT_ERROR_CODE]
