export const USER_ERROR_CODE = {
  REQUEST_SIGNUP_NOT_FOUND: 'U-0001',
  REQUEST_SIGNUP_ALREADY_EXISTED: 'U-0002',
  AUTHENTICATION_NOT_FOUND: 'U-0003',
  APPROVE_NECESSARY_ROLE: 'U-0004',
  ALREADY_SIGNED_USER: 'U-0005',
  USER_NOT_FOUND: 'U-0006',
  ROLE_ADMIN_CANT_REQUEST: 'U-0007',
  INACTIVE_USER: 'U-0008',
  INVALID_REFRESH_TOKEN: 'U-0009',
  TOKEN_EXPIRED: 'U-0010',
} as const

export type UserErrorCode = (typeof USER_ERROR_CODE)[keyof typeof USER_ERROR_CODE]
